### ISSUE TITLE
Support for QuestGuru_Classic

### ISSUE THREAD

**Issue by austinrr** [butter-cookie-kitkat/ButterQuestTracker#11]
When clicking on a quest it opens the Blizzard quest log but if another quest log such as QuestGuru_Classic is installed it should open that quest log.

https://www.curseforge.com/wow/addons/questguru_classic

**Comment by cecilia-sanare** [comment]
Hey there @austinrr thanks for submitting an issue!

I just released [v1.4.0](https://www.curseforge.com/wow/addons/butter-quest-tracker/files/2793673) to CurseForge that now supports QuestGuru, let me know if you run into any issues!

**Comment by austinrr** [comment]
Works!
