### ISSUE TITLE
Anchor point resets on /reload or relog

### ISSUE THREAD

**Issue by Nillx** [butter-cookie-kitkat/ButterQuestTracker#15]
Quest anchor point resets every time when i reload my UI or relog. Im not sure what is causing that but i need to alt move them every time.

**Comment by cecilia-sanare** [comment]
Interesting, I'm unable to reproduce this on my end.

Can you try enabling `Developer Mode` under the Advanced tab and providing a screenshot of your chat window after moving the dialog?

Specifically I'm expecting to see a `Moved to (x, y).` in the chat log.

**Comment by Nillx** [comment]
19:35 [ButterQuestTracker]:  Moved to (-113.91978565761, -178.67328797284).

**Comment by cecilia-sanare** [comment]
Interesting so its picking it up and storing it at the very least.

If it isn't too much trouble, can you try resetting BQT and see if it persists?

**Comment by Nillx** [comment]
Its happening even without other addons installed. Resetting does nothing.

**Comment by Nillx** [comment]
Here a comparison after alt-placing it and the position after /reload https://imgur.com/a/IFLMVrH

**Comment by cecilia-sanare** [comment]
@Nillx I see it now!

It was just so subtle that I didn't really notice.
Thanks for taking the time to walk me through that, I'll let you know when its resolved!

**Comment by Nillx** [comment]
Im happy to help

**Comment by cecilia-sanare** [comment]
This should be resolved in [1.5.1](https://www.curseforge.com/wow/addons/butter-quest-tracker/files/2794063) let me know if you run into any other issues!

**Comment by Nillx** [comment]
Fixed, thanks.
