### ISSUE TITLE
Completed quest objectives in different color - easier to see.

### ISSUE THREAD

**Issue by Nillx** [butter-cookie-kitkat/ButterQuestTracker#19]
How difficult it will be to add an option that change the color of completed objectives?

Example here: https://imgur.com/a/gn2OgxU

7/7 ones should be in bright white while the ones that are still 6/7 5/7 should be the same darker white color. It will be much easier to spot the ones that you miss. Think its like that on Retail.

**Comment by cecilia-sanare** [comment]
Hmm, this functionality actually already exists but something must have broken it.

I'll look into it.

**Comment by cecilia-sanare** [comment]
Hey @Nillx this issue show now be resolved in [1.6.4](https://www.curseforge.com/wow/addons/butter-quest-tracker/files/2795330)!

**Comment by Nillx** [comment]
Thanks 👍

**Comment by cecilia-sanare** [comment]
Out of curiosity @Nillx have you experienced any issues with the tracker flickering?

> **By fireundubh:**
> 
> The 1.6.4 Quests frame repeatedly flickers, making it unusable. I was flying at the time.

**Comment by Nillx** [comment]
Nope i did not saw any flickering

**Comment by Nillx** [comment]
Switched to 1.7.0, no flickering so far.
