### ISSUE TITLE
Add the ability to display quests by their Zone

### ISSUE THREAD

**Issue by cecilia-sanare** [butter-cookie-kitkat/ButterQuestTracker#25]
## Description

Users should be able to optionally display quests by their zone (could also be subzone, class, or profession).

Users should also be able to fold a given zone.

**Comment by Sythalin** [comment]
I was just coming here to post this exact suggestion.  Most of the time I want to have a quick glance at the zones I have quests in, not necessarily the quests themselves since I'm not in that zone.  See Monkey Quest:

https://media.forgecdn.net/attachments/93/56/monkeyquest-monkeyquest2.jpg

**Comment by cecilia-sanare** [comment]
Bumping to 1.9.0 as there are already quite a few functional and visual changes in 1.8.0

**Comment by cecilia-sanare** [comment]
There's a working prototype of this functionality in the [zone-headers](https://github.com/butter-cookie-kitkat/ButterQuestTracker/tree/zone-headers) branch if anyone wants to check it out.

I opted not to release it with [1.9.0-beta.1](https://github.com/butter-cookie-kitkat/ButterQuestTracker/releases/tag/1.9.0-beta.1) due to how little it has been tested and how much it changes the TrackerHelper code.

**Comment by cecilia-sanare** [comment]
Hey @Sythalin this feature was just released in [1.9.0-beta.2](https://www.curseforge.com/wow/addons/butter-quest-tracker/files/2800763).

Let me know if you run into any issues!
