### ISSUE TITLE
Add option to adjust background color and opacity

### ISSUE THREAD

**Issue by ghost** [butter-cookie-kitkat/ButterQuestTracker#27]
The quest tracker is not always easy to read. I know I can make the font larger but being able to adjust the background color and opacity would make it easier to see.

**Comment by cecilia-sanare** [comment]
Hey @PocketAppZ!

This functionality was just released in [1.8.0-beta.1](https://www.curseforge.com/wow/addons/butter-quest-tracker/files/2797615), if you happen to try it out let me know if you run into any issues!
