### ISSUE TITLE
WoW Classic: v1.72

### ISSUE THREAD

**Issue by Havenloft** [butter-cookie-kitkat/ButterQuestTracker#36]
New errors on newest update:

1x ...aceButterQuestTracker\ButterQuestTracker-1.7.2.lua:630: attempt to index field 'Log' (a nil value)
...aceButterQuestTracker\ButterQuestTracker-1.7.2.lua:630: in function `?'
...aceButterQuestTracker\ButterQuestTracker-1.7.2.lua:707: in function <...aceButterQuestTracker\ButterQuestTracker.lua:706>

Locals:
self = <unnamed> {
 0 = <userdata>
 ToggleContextMenu = <function> defined @ButterQuestTracker\ButterQuestTracker.lua:426
 CreateHeader = <function> defined @ButterQuestTracker\ButterQuestTracker.lua:350
 CreateTruncatedHeader = <function> defined @ButterQuestTracker\ButterQuestTracker.lua:360
 CreateFont = <function> defined @ButterQuestTracker\ButterQuestTracker.lua:338
 CreateReadyToTurnIn = <function> defined @ButterQuestTracker\ButterQuestTracker.lua:395
 DB = <table> {
 }
 ShowWowheadPopup = <function> defined @ButterQuestTracker\ButterQuestTracker.lua:46
 Clear = <function> defined @ButterQuestTracker\ButterQuestTracker.lua:223
 RefreshQuestWatch = <function> defined @ButterQuestTracker\ButterQuestTracker.lua:186
 CreateQuestHeader = <function> defined @ButterQuestTracker\ButterQuestTracker.lua:371
 ResetOverrides = <function> defined @ButterQuestTracker\ButterQuestTracker.lua:686
 MODIFIER_STATE_CHANGED = <function> defined @ButterQuestTracker\ButterQuestTracker.lua:699
 Refresh = <function> defined @ButterQuestTracker\ButterQuestTracker.lua:236
 UpdateQuestWatch = <function> defined @ButterQuestTracker\ButterQuestTracker.lua:199
 OnEvent = <function> defined @ButterQuestTracker\ButterQuestTracker.lua:706
 CreateQuestSummary = <function> defined @ButterQuestTracker\ButterQuestTracker.lua:404
 ADDON_LOADED = <function> defined @ButterQuestTracker\ButterQuestTracker.lua:603
 SetClickFrame = <function> defined @ButterQuestTracker\ButterQuestTracker.lua:509
 Initialize = <function> defined @ButterQuestTracker\ButterQuestTracker.lua:114
 CreateQuestObjective = <function> defined @ButterQuestTracker\ButterQuestTracker.lua:413
 RefreshFrame = <function> defined @ButterQuestTracker\ButterQuestTracker.lua:163
 RefreshPosition = <function> defined @ButterQuestTracker\ButterQuestTracker.lua:153
 RefreshSize = <function> defined @ButterQuestTracker\ButterQuestTracker.lua:158
}
addon = "ButterQuestTracker"
(*temporary) = nil
(*temporary) = <table> {
 MANUALLY_TRACKED_QUESTS = <table> {
 }
 QUESTS_LAST_UPDATED = <table> {
 }
}
(*temporary) = "QUESTS_LAST_UPDATED"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'Log' (a nil value)"
NAME = "ButterQuestTracker"
ns = <table> {
 CONSTANTS = <table> {
 }
}
QWH = <table> {
 KeepHidden = <function> defined @ButterQuestTracker\QuestWatchHelper\QuestWatchHelper.lua:114
 GetFrame = <function> defined @ButterQuestTracker\QuestWatchHelper\QuestWatchHelper.lua:30
 IsAutomaticQuestWatchEnabled = <function> defined @ButterQuestTracker\QuestWatchHelper\QuestWatchHelper.lua:34
 SetAutomaticQuestWatch = <function> defined @ButterQuestTracker\QuestWatchHelper\QuestWatchHelper.lua:38
 OnQuestWatchUpdated = <function> defined @ButterQuestTracker\QuestWatchHelper\QuestWatchHelper.lua:110
 BypassWatchLimit = <function> defined @ButterQuestTracker\QuestWatchHelper\QuestWatchHelper.lua:42
}
QLH = <table> {
 OnQuestUpdated = <function> defined @ButterQuestTracker\QuestLogHelper\QuestLogHelper.lua:75
 SetQuestsLastUpdated = <function> defined @ButterQuestTracker\QuestLogHelper\QuestLogHelper.lua:79
 GetQuestSummary = <function> defined @ButterQuestTracker\QuestLogHelper\QuestLogHelper.lua:352
 ToggleQuest = <function> defined @ButterQuestTracker\QuestLogHelper\QuestLogHelper.lua:130
 GetDifficulty = <function> defined @ButterQuestTracker\QuestLogHelper\QuestLogHelper.lua:167
 GetWatchedQuests = <function> defined @ButterQuestTracker\QuestLogHelper\QuestLogHelper.lua:295
 AbandonQuest = <fu

----------------------------

2x ...aceButterQuestTracker\ButterQuestTracker-1.7.2.lua:237: attempt to index field 'Log' (a nil value)
...aceButterQuestTracker\ButterQuestTracker-1.7.2.lua:237: in function `Refresh'
ButterQuestTracker\Options-Options.lua:36: in function <ButterQuestTracker\Options.lua:34>
[C]: ?
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-78.lua:51: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:49>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-78.lua:843: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:664>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-78.lua:895: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:883>
[C]: ?
...eBroker_BagFu\Libs\AceGUI-3.0\AceGUI-3.0-40.lua:72: in function <...eBroker_BagFu\Libs\AceGUI-3.0\AceGUI-3.0.lua:70>
...eBroker_BagFu\Libs\AceGUI-3.0\AceGUI-3.0-40.lua:290: in function `Fire'
...tlas\Libs\AceGUI-3.0-40\widgets\AceGUIWidget-Slider.lua:69: in function <...tlas\Libs\AceGUI-3.0\widgets\AceGUIWidget-Slider.lua:60>
[C]: in function `SetValue'
...tlas\Libs\AceGUI-3.0-40\widgets\AceGUIWidget-Slider.lua:111: in function <...tlas\Libs\AceGUI-3.0\widgets\AceGUIWidget-Slider.lua:99>

**Comment by cecilia-sanare** [comment]
Hey @Havenloft I appreciate you bringing this to my attention and I'm sorry you had to experience this.

I've just published [1.7.3](https://www.curseforge.com/wow/addons/butter-quest-tracker/files/2798653) which resolves this issue, can you check it out and let me know if you run into any issues?

Thanks!

**EDIT: I've also archived 1.7.2 to prevent users from downloading this broken version.**
