### ISSUE TITLE
A few issues since the last update 1.8.0

### ISSUE THREAD

**Issue by Nillx** [butter-cookie-kitkat/ButterQuestTracker#38]
For some reason sometimes the auto update feature does not work and its not tracking quest progress after killing a mob or looting q item. Also if i shift click and hide a quest, it hides Questie icons on the map too (quest objective icons). Is this a feature or a bug?

**Comment by cecilia-sanare** [comment]
Hey @Nillx,

> For some reason sometimes the auto update feature does not work and its not tracking quest progress after killing a mob or looting an item.

Not sure about the killing / looting issue, but I fixed quite a few issues with auto tracking in v1.8.1 so let me know if that resolves it for you.

> Also if i shift click and hide a quest, it hides Questie icons on the map too (quest objective icons). Is this a feature or a bug?

This is indeed a feature, although when I was implementing it I debated on adding a toggle to turn it on rather then defaulting it to on.

**Comment by Nillx** [comment]
Interesting. Ill try 1.8.1 and play a bit with that new feature to see how i feel. It surely made me feel confused for awhile until i figured out what is causing it :D

**Comment by cecilia-sanare** [comment]
@Nillx yeah, that very confusion is exactly why I'm going to make this feature opt-in.

Making the user explicitly enable it will make it incredibly clear why their icons are disappearing.
