### ISSUE TITLE
1.9.0 RC1 quests randomly starting to track while changing zones

### ISSUE THREAD

**Issue by Nillx** [butter-cookie-kitkat/ButterQuestTracker#46]
For some reason this quests always pop on the screen when im flying on the FP or changing zones. 

[![Quests](https://i.imgur.com/f9TvH9S.jpg)](https://imgur.com/a/doerVa4)

This are my settings...

[![Settings](https://i.imgur.com/HcYfgzR.jpg)](https://imgur.com/a/F350SJG)

**Comment by Nillx** [comment]
Also when trying to hide Delivery to Magatha with shift click, it hides both quests 

[![Quests](https://i.imgur.com/HUJDhfG.jpg)](https://i.imgur.com/HUJDhfG.jpg)

**Comment by cecilia-sanare** [comment]
Hmm, I'm having difficulty reproducing this.

Can you try turning on Developer Mode and shoot me a screenshot of the chat when it occurs?
Also send me a screenshot if you see the quest containers (green boxes) grow larger (vertically) then the quest content.

![image](https://user-images.githubusercontent.com/9692284/66164067-6b379b80-e5f7-11e9-894b-21c48db3d590.png)

**Comment by Nillx** [comment]
I cannot reproduce it again.. im not sure what was causing it. Ill post screenshots with the dev mode if i see it again.

**Comment by cecilia-sanare** [comment]
Hey @Nillx, can you do me a favor?

Can you pull down 1.9.0-rc.2 and take a screenshot of all the settings screens?
The reason I ask is that I expected them to look like the following... 

_Notice how most of the inputs are on one line, whereas they're overflowing on yours._

### Filters & Sorting

![image](https://user-images.githubusercontent.com/9692284/66180946-82e14500-e634-11e9-9abe-0859afa4453c.png)

### Visual Settings

![image](https://user-images.githubusercontent.com/9692284/66180954-8bd21680-e634-11e9-81ed-87788f654d20.png)

### Frame Settings

![image](https://user-images.githubusercontent.com/9692284/66180969-94c2e800-e634-11e9-883b-35334a7233ea.png)

### Advanced

![image](https://user-images.githubusercontent.com/9692284/66180976-9c828c80-e634-11e9-97cd-7bc46adbbe2c.png)

**Comment by Nillx** [comment]
https://imgur.com/a/M2u8YUY
