### ISSUE TITLE
ButterQuestTrackerConfig is not yet defined on load, Curse v1.0.0 release

### ISSUE THREAD

**Issue by Ketho** [butter-cookie-kitkat/ButterQuestTracker#5]
Error message when loading up:
```lua
Date: 2019-09-23 16:16:37
ID: 1
Error occured in: Global
Count: 1
Message: ...rface\AddOns\ButterQuestTracker\utilities\logger.lua line 5:
   attempt to index global 'ButterQuestTrackerConfig' (a nil value)
Debug:
   ...rface\AddOns\ButterQuestTracker\utilities\logger.lua:5: Debug()
   ...rface\AddOns\ButterQuestTracker\utilities\logger.lua:19: Info()
   ...ace\AddOns\ButterQuestTracker\ButterQuestTracker.lua:504: ?()
   ...ace\AddOns\ButterQuestTracker\ButterQuestTracker.lua:543:
      ...ace\AddOns\ButterQuestTracker\ButterQuestTracker.lua:542
AddOns:
  ButterQuestTracker, v1.0.0
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=72)
```
It should already be fixed but v1.0.0 doesn't seem to match the one on Curse
https://github.com/butter-cookie-kitkat/ButterQuestTracker/blob/1.0.0/ButterQuestTracker.lua#L504

**Comment by cecilia-sanare** [comment]
Hey @Ketho thanks for taking the time to submit an issue, not sure how I allowed this one to slip me by.

This issue should now be resolved in [1.1.0](https://www.curseforge.com/wow/addons/butter-quest-tracker/files/2792276), however feel free to reopen this issue if its still occurring!
