### ISSUE TITLE
Two Quest tracker UI elements

### ISSUE THREAD

**Issue by ragnarok1234** [butter-cookie-kitkat/ButterQuestTracker#52]
## Bug description

I currently have two quest tracker UI elements. Even though I did a complete reinstall of all of my addons after having removed the WTF folder, Cache folder and Interface folder it still persisted, which pointed me towards the save variables so I went ahead and deleted those too, which did not resolve the issue.
## Screenshots

![bild](https://user-images.githubusercontent.com/56176387/66240737-c653b600-e6fd-11e9-97f1-e80052c8bcd9.png)

**Butter Quest Tracker Version:**   1.8.5 off of Curse

**Comment by ragnarok1234** [comment]
The issue is resolved whenever I disable the automatic tracking option via the addon options interface

**Comment by ragnarok1234** [comment]
![bild](https://user-images.githubusercontent.com/56176387/66241851-52ff7380-e700-11e9-8ee0-9d620855aafd.png)
addon disabled yet still showing up

**Comment by ragnarok1234** [comment]
can confirm that this issue is caused by the Questie addons quest tracker.

**Comment by cecilia-sanare** [comment]
Yup, as you’ve already discovered that second tracker is Questie. 
I’m guessing you already figured out that you can disable it as well. 

Closing this issue as it isn’t actually a bug.
