### ISSUE TITLE
I see 2 quest lists

### ISSUE THREAD

**Issue by Holytush** [butter-cookie-kitkat/ButterQuestTracker#64]
## Question
I am sure I am missing something obvious, but I see the Classic Quest List along with Butter.   How do I hide the Classic list?

**Comment by Holytush** [comment]
Never mind.  Found out it was the Questie tracker I was seeing.  Disable it and all is well.

**Comment by cecilia-sanare** [comment]
Glad you were able to figure it out!

Let me know if you run into any other issues!

**Comment by Holytush** [comment]
Awesome response time and EXCELLENT ADDON....

**Comment by Holytush** [comment]
Any chance you know how to move the location of the casting bar in WOW
classic?

**Comment by cecilia-sanare** [comment]
I assume by the casting bar you mean this?

![image](https://user-images.githubusercontent.com/9692284/66276348-af28db80-e857-11e9-9396-67f352d9a7ff.png)

If so then as far as I know you can't without some sort of addon.

**Comment by Holytush** [comment]
I agree that an addon is needed.   But cannot find one.  Any chance of your
doing your magic here and enhancing your Butter to include moving that?

**Comment by cecilia-sanare** [comment]
Butter Quest Tracker is focused on improving the quest tracker.
Adding functionality to move the castbar wouldn't really make sense.

Quartz is a castbar addon that enables your to adjust all sorts of things including the position.

https://www.curseforge.com/wow/addons/quartz

**Comment by Holytush** [comment]
TY.

**Comment by Holytush** [comment]
That worked perfectly.  TYVM
