### ISSUE TITLE
Quest Proximity lag

### ISSUE THREAD

**Issue by FourOne** [butter-cookie-kitkat/ButterQuestTracker#65]
If i use "Quest Proximity" for sorting, tested with Questie and ClassicCodex, game  starts to lag. Had around 16 Quest, as soon as i set other options for sorting lag was gone.

**Comment by cecilia-sanare** [comment]
This is because we redraw the tracker every 4 seconds given the player has actually moved.

Ideally we'd instead do a partial update and just reorder the existing items, however it's a limitation in how the Tracker is currently written.

I'll try and come up with a workaround for 1.9, but not sure if I'll be successful.

**Comment by cecilia-sanare** [comment]
Hey @FourOne this issue should either be resolved or at the very least mitigated in [1.9.5 ](https://www.curseforge.com/wow/addons/butter-quest-tracker/files/2803895)
as sorting no longer requires the entire frame to be redrawn.

Let me know if you're still hitting performance issues with the new version.

**Comment by FourOne** [comment]
Working now, ty for your great and fast work :D

Proximity was the only thing i was rly missing, im so used to it from retail.

**Comment by cecilia-sanare** [comment]
I didn’t realize retail had sorting by quest proximity. 

I’ve been trying to figure out how to get it to work on multiple maps on retail.

**Comment by FourOne** [comment]
Its not in the options anymore, they removed it with Legion. But u can enable it with "/console trackQuestSorting proximity".

**Comment by cecilia-sanare** [comment]
Thanks for the information! I’ve seen a few dumps of blizzards native frame source code lying around so this should help in narrowing down the code making it work!

I really appreciate it!

**Comment by FourOne** [comment]
I think even before Legion most ppl didn't know this option exists, u had to right click the top of the objective tracker - kinda hidden, and then they removed because it was not used by that many players :D
