### ISSUE TITLE
Blizzard default quest tracker overlapping BQT

### ISSUE THREAD

**Issue by boidhe** [butter-cookie-kitkat/ButterQuestTracker#68]
This may be better suited as a question, but I also feel this may be a bug. The default Blizzard quest tracker is still visible while using Butter Quest Tracker.

If I untrack a quest to make the Blizzard tracker disappear, it affects the quests listed by BQT. I feel the default tracker should be removed (hidden) if BQT is enabled.

I'm not sure how to classify this. Is this a bug? I'm surprised this hasn't been brought up by others, so I'm wondering if another mod is doing this.

I'm not using any other UI mods that modify the default tracker, and my list of mods is kept to a minimum.

**Comment by cecilia-sanare** [comment]
Hey @johndeboyd, thanks for taking the time to submit an issue!

Interesting, Butter Quest Tracker is supposed to hide the Blizzard tracker by default.
Which version of the tracker are you using?

Also can you provide a screenshot of the issue and your addons as well?

**Comment by boidhe** [comment]
WoW client version 1.13.2.31882
BQT version 1.9.4 (newest from Twitch client)

Mod list and screenshot of bug:
https://imgur.com/a/ElokGXh

Please note: Ark Inventory, Talented Spec, and Deadly Boss Mod are disabled in WoW.

**Comment by cecilia-sanare** [comment]
@johndeboyd That isn't the Blizzard tracker, that's Questie's Tracker.

You can disable it by going into Questie's Tracker Settings.

**Comment by boidhe** [comment]
You sir are a hero. Thank you. Sorry to waste your time, but I appreciate your insight and guidance.

**Comment by cecilia-sanare** [comment]
No worries, it's a pretty common mistake actually.

I honestly think most people don't even expect Questie to have a tracker, haha.
