### ISSUE TITLE
Error when Switching Zones with Quest Proximity Sorting Enabled

### ISSUE THREAD

**Issue by Spiricore** [butter-cookie-kitkat/ButterQuestTracker#69]
I received this error after hearthing to a zone with a quest turn-in in it. I have Current Zone Only selected and filtering by Quest Proximity.

Cheers, and thanks for this addon!

> ID: 1
Error occured in: Global
Count: 1
Message: ...ace\AddOns\ButterQuestTracker\ButterQuestTracker.lua line 500:
   attempt to perform arithmetic on local 'order' (a nil value)
Debug:
   ...ace\AddOns\ButterQuestTracker\ButterQuestTracker.lua:500: Sort()
   ...ace\AddOns\ButterQuestTracker\ButterQuestTracker.lua:240:
      ...ace\AddOns\ButterQuestTracker\ButterQuestTracker.lua:229
   ..\SharedXML\C_TimerAugment.lua:16:
      ..\SharedXML\C_TimerAugment.lua:14
Locals:
self = <table> {
 GetQuestHeader = <function> defined @Interface\AddOns\ButterQuestTracker\ButterQuestTracker.lua:457
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:367
 ToggleContextMenu = <function> defined @Interface\AddOns\ButterQuestTracker\ButterQuestTracker.lua:774
 OnInitialize = <function> defined @Interface\AddOns\ButterQuestTracker\ButterQuestTracker.lua:42
 NewModule = <function> defined @Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:235
 EnableModule = <function> defined @Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetModule = <function> defined @Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:210
 IterateEmbeds = <function> defined @Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:442
 RefreshView = <function> defined @Interface\AddOns\ButterQuestTracker\ButterQuestTracker.lua:510
 defaultModuleLibraries = <table> {
 }
 ShowWowheadPopup = <function> defined @Interface\AddOns\ButterQuestTracker\ButterQuestTracker.lua:141
 RefreshQuestWatch = <function> defined @Interface\AddOns\ButterQuestTracker\ButterQuestTracker.lua:253
 GetQuestInfo = <function> defined @Interface\AddOns\ButterQuestTracker\ButterQuestTracker.lua:294
 hiddenContainers = <table> {
 }
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:409
 name = "ButterQuestTracker"
 IsEnabled = <function> defined @Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:451
 orderedModules = <table> {
 }
 DisableModule = <function> defined @Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:350
 questContainers = <table> {
 }
 LogInfo = <function> defined @Interface\AddOns\ButterQuestTracker\ButterQuestTracker.lua:877
 playerPosition = <table> {
 }
 questProximityTimer = <table> {
 }
 GetTrackerHeader = <function> defined @Interface\AddOns\ButterQuestTracker\ButterQuestTracker.lua:447
 tracker = TrackerHelperFrame1 {
 }
 baseName = "ButterQuestTracker"
 IsModule = <function> defined @Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:468
 db = <table> {
 }
 SetDefaultModuleState = <function> defined @Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:387
 LogTrace = <function> defined @Interface\AddOns\ButterQuestTracker\ButterQuestTracker.lua:881
 LogWarn = <function> defined @Interface\AddOns\ButterQuestTracker\ButterQuestTracker.lua:873
 SetEnabledState = <function> defined @Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:424
 Debug = <function> defined @Interface\AddOns\ButterQuestTracker\ButterQuestTracker.lua:863
 enabledState = true
 LogError = <function> defined @Interface\AddOns\ButterQuestTracker\ButterQuestTracker.lua:869
 ShouldWatchQuest = <function> defined @Interface\AddOns\ButterQuestTracker\ButterQuestTracker.lua:274
 Sort = <function> defined @Interface\AddOns\ButterQuestTracker\ButterQuestTracker.lua:473
 questsContainer = TrackerHelperContainer4 {
 }
 Enable = <function> defined @Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:294
 ResetOverrides = <function> defined @Interface\AddOns\ButterQuestTracker\ButterQuestTracker.lua:857
 IterateModules = <function> defined @Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:437
 UpdateQuestWatch = <function> defined @Interface\AddOns\ButterQuestTracker\ButterQuestTracker.lua:266
 UpdateQuestProximityTimer = <function> defined @Interface\AddOns\ButterQuestTracker\ButterQuestTracker.lua:224
 OnEnable = <function> defined @Interface\AddOns\ButterQuestTracker\ButterQuestTracker.lua:124
 GetName = <function> defined @Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:279
 defaultModuleState = true
 Disable = <function> defined @Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:314
}
quests = <table> {
 2500 = <table> {
 }
}
keys = <table> {
 1 = 2500
}
questIDToOrderMap = <table> {
 2500 = 1
}
zoneToOrderMap = <table> {
 Loch Modan = 1
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = TrackerHelperContainer`

**Comment by cecilia-sanare** [comment]
Hey @Spiricore, thanks for taking the time to submit an issue.

This is actually a really interesting error.
I'm guessing this is a race condition between your zone changing and the quest proximity timer.

Basically the quests had already updated, but the view hadn't refreshed.

As such when it attempted to sort the (now outdated) zones it threw an 
error since those zones no longer existed in your list of tracked quests.

**Comment by cecilia-sanare** [comment]
closed via ed94fb79e0db88bf05c4cde63b42af9876ce523e

**Comment by cecilia-sanare** [comment]
Hey @Spiricore, a fix for this should now be available in [1.9.7](https://www.curseforge.com/wow/addons/butter-quest-tracker/files/2804040).

Let me know if you run into any other issues!
