### ISSUE TITLE
Add an option to disable the quests header

### ISSUE THREAD

**Issue by Nillx** [butter-cookie-kitkat/ButterQuestTracker#7]
-Can you let us somehow untrack quests? Like Shift Click on it to hide it
-I would love an option to hide the Quests [#/#] on the top.

**Comment by cecilia-sanare** [comment]
Hey @Nillx!

> Can you let us somehow untrack quests? Like Shift Click on it to hide it

You're correct in thinking that allowing users to hide a quest via some button combo is indeed a small change. 

The difficulty comes in enable users to then re-add those same quests back onto the tracker. Blizzard's built-in library for the quest log only enables you to watch 5 quests at once, a few trackers get around this limitation by effectively overwriting the built-in blizzard library for watching quests which is a fairly large change.

I've opened #8 to track this feature request.

> I would love an option to hide the Quests [#/#] on the top.

This is a fairly easy change. Would you want to hide the entire "Quests (10/20)"? or just the numbers?

**Comment by Nillx** [comment]
Whole Quests (10/20) tab. Modern Quest Watch can hide the quests with shift click, now sure how does it work tho :)

**Comment by cecilia-sanare** [comment]
Yup, the way Modern Quest Watch works is that it's actually adding functionality to the built-in quest tracker such as auto-watching and the ability to drag the tracker around.

There are definitely pros and cons to this approach.

**Pros**

- You don't have to constantly tell the built-in quest tracker to hide. ([Example 1](https://github.com/butter-cookie-kitkat/ButterQuestTracker/blob/56862a322d5b90274bb73e2a39d0cab030bd4a92/ButterQuestTracker.lua#L631-L635) and [Example 2](https://github.com/butter-cookie-kitkat/ButterQuestTracker/blob/56862a322d5b90274bb73e2a39d0cab030bd4a92/ButterQuestTracker.lua#L192-L194))
- You can utilize the functionality blizzard has already developed rather then developing a custom tracker.

**Cons**

- Limited to 5 quests unless you override the built-in quest watch library by blizzard. (see [Kaliel's Tracker](https://www.curseforge.com/wow/addons/kaliels-tracker-classic))

I ended up going down the route of writing our own tracker frame to bypass the 5 quest limitation.

**Comment by cecilia-sanare** [comment]
Hey @Nillx you can now hide the quest headers in [v1.2.0](https://www.curseforge.com/wow/addons/butter-quest-tracker/files/2793488). 🎉 

Let me know if you run into any issues!

**Comment by Nillx** [comment]
Thanks, works great.

**Comment by cecilia-sanare** [comment]
Hey @Nillx!

Just thought I'd give you a heads up that a beta version of v1.6.1 was just released that supports tracking and untracking quests.
If no bugs are discovered before the end of today I'll most likely promote it to a release build.

However for now you can test it out by swapping to the Beta Release on the Twitch App!

**Comment by Nillx** [comment]
Works great from what i saw so far! Thanks. Maybe a tiny suggestion, can you add a shortcut like shift+left click to untrack the quest? Like on retail.

**Comment by cecilia-sanare** [comment]
Hey @Nillx I just released v1.6.3 with the ability to shift+click the quests to untrack them.
As such linking quests in chat has been moved to ctrl+click.

Let me know if you run into any issues!

**Comment by Nillx** [comment]
Works perfectly thanks!
