### ISSUE TITLE
Improve Retail WoW Built-In Proximity Sorting

### ISSUE THREAD

**Issue by cecilia-sanare** [butter-cookie-kitkat/ButterQuestTracker#70]
## Bug description

Currently it only works for the current map. 

## Resources

- https://github.com/DCMau/QuestWatchSorting/blob/master/QuestWatchSorting.lua

**Butter Quest Tracker Version:** 1.9

**Comment by nick-woodward** [comment]
Closed via 0b53cd30ff2a27719fe314ea472a61d98bca2f80
