### ISSUE TITLE
Tracker Doesn't Save Position

### ISSUE THREAD

**Issue by Spiricore** [butter-cookie-kitkat/ButterQuestTracker#71]
//Edit: Seems to be a conflict with ElvUI, even with ObjectiveTracker Enhancements off through it.
Me again! Thanks for fixing the last bug.

I can't seem to get the tracker to save its position on the far left side of the screen. Even with frame lock on or off, it resets after a reloadui or relog. Attached is a screenshot of where it always resets to.
![WoWScrnShot_100819_180608](https://user-images.githubusercontent.com/5013041/66444003-504d9880-e9f6-11e9-99af-29bacec9ce1c.jpg)

**Comment by cecilia-sanare** [comment]
Hey Spiricore, I'm struggling to reproduce this on my end. 
Can you disable your addons and verify if it still occurs?
