### ISSUE TITLE
[1.9.8] ElvUI Quest Watch Frame:  Cursor Detection

### ISSUE THREAD

**Issue by Wdavis4692** [butter-cookie-kitkat/ButterQuestTracker#74]
Old functionality in 1.9.7:  https://gyazo.com/05743ce18ff17f91f51c865f615dbeb6

New functionality in 1.9.8:  https://gyazo.com/edcd02c4ea4413da79aeda52421059f9

The actual quest title no longer generates a tooltip or lights up when moused-over.  There's a dead spot covering most of the title, as you can see in the second Gyazo clip.  There is, strangely, a sliver of area just above the title which _does_ register, which is also visible in the clip!

I have tested this with only BQT and ElvUI v.1.14 (latest) enabled and can confirm no other addons are causing a taint here.  Also, If I disable ElvUI, the issue goes away entirely, so I can also confirm it is something to do with the specific change in 1.9.8's patch notes that refers to ElvUI positioning.

_**Important Note:** that Clicking in the area that doesn't light up or generate a tooltip would ordinarily do nothing, but since ElvUI has in-built functionality to click tracked quests to open the journal, it still does something -- don't mistake this for BQT functioning weirdly!  This is just us clicking through to ElvUI's functionality _beneath_ BQT, due to the absence of the BQT frame being detected underneath the cursor.  

Specifically,  ElvUI just opens the quest log to that quest, and doesn't close again on a subsequent click on the quest title.   I mistook this for a BQT issue until I realised my mistake..._

**Comment by cecilia-sanare** [comment]
Hey @Wdavis4692 thanks for submitting an issue!

This should now be resolved in [1.9.9](https://www.curseforge.com/wow/addons/butter-quest-tracker/files/2807513), let me know if you run into any other issues!
