### ISSUE TITLE
Question: Automatically Hide QH Icons

### ISSUE THREAD

**Issue by anthonygauthier** [butter-cookie-kitkat/ButterQuestTracker#76]
**What does Automatically Hide QH Icons do?**

Not sure if I'm the one that's stupid or overthinking it, but I'm not sure what that feature does. Even after quickly scanning the [code](https://github.com/butter-cookie-kitkat/ButterQuestTracker/blob/master/LibQuestHelpers/LibQuestHelpers.lua). 

From what I understand it hides any icons (minmap/map) of newly tracked quests?

**Comment by cecilia-sanare** [comment]
Hey @delirius325!

If you untrack a quest it should disappear from your map / minimap.

See [here](https://github.com/butter-cookie-kitkat/ButterQuestTracker/blob/70e9d61df1a3d3f8927518115de561c7349bd48b/LibQuestHelpers/LibQuestHelpers.lua#L76-L82) where it hides or shows an icon based on its watched status.

**Comment by anthonygauthier** [comment]
Thanks for the quick response @cecilia-sanare!
