### ISSUE TITLE
Setting objective font size to 11 causes objective text to crash with quest header

### ISSUE THREAD

**Issue by speedwaystar** [butter-cookie-kitkat/ButterQuestTracker#78]
## Bug description

See header

## Screenshots

![image](https://user-images.githubusercontent.com/82137/66825955-e5640a80-ef7d-11e9-9bd4-2ca4175d97c5.png)

**Butter Quest Tracker Version:** 

1.19.11

**Comment by cecilia-sanare** [comment]
Hey @speedwaystar, just quickly looked into this and I've pushed out a fix that should resolve it in [1.9.12](https://www.curseforge.com/wow/addons/butter-quest-tracker/files/2809876).

Let me know if you run into any other issues!
