### ISSUE TITLE
[1.9.12] Enabling/disabling zone headers makes "recently updated" sorting go wrong

### ISSUE THREAD

**Issue by fleetcommand** [butter-cookie-kitkat/ButterQuestTracker#79]
## Bug description

If you enable the zone headers and later disable them, they will be still considered when sorting quests by "recently updated". The expected result would be that if you have zone headers disabled AND sorting by recently updated, the recently updated quest should go to the top. However, if you had previously enabled the zone headers, they will still be considered for sorting even after disabling them. Please see the below two screenshots where I have marked the boundaries between the zones. You can observe that the quest is moved only two places up after update instead of being placed to the top.

## Screenshots

Quest position before update:

![before](https://user-images.githubusercontent.com/614523/67632582-88355680-f8a5-11e9-8b8a-bdada7b0878f.jpg)

Quest position after update:

![after](https://user-images.githubusercontent.com/614523/67632584-8bc8dd80-f8a5-11e9-80a2-2f9b3247dde4.jpg)

**Butter Quest Tracker Version:** 1.9.12

**Comment by cecilia-sanare** [comment]
Hey @fleetcommand thanks for taking the time to submit an issue!

I think I may know what's causing this.
Did the issue happen to resolve itself when you relogged?

**Comment by fleetcommand** [comment]
Hi!

Sorry, I was not home this week so I could not check sooner. Relogging does not resolve this issue. I just started WoW the first time since last Sunday, headed to this quest and got another hardened shell to move from 4/9 to 5/9. Unfortunately the quest position did not update, it is still in the same position. Also tried switching sorting method in the Options (switch to "Don't sort" and then back to "Recently updated", but unfortunately it didn't help).

**Comment by cecilia-sanare** [comment]
I'm having a tough time reproducing this issue.

Can you add `{{lastUpdated}}` to your Quest Header Format and send me an updated screenshot?

**Comment by fleetcommand** [comment]
Certainly. Please see the below screenshot:

![WoWScrnShot_110119_175759](https://user-images.githubusercontent.com/614523/68041601-35a6d080-fcd1-11e9-8e5d-1b7ecfb4f816.jpg)

**Comment by cecilia-sanare** [comment]
So, apparently I should have read the [documentation](https://wowwiki.fandom.com/wiki/API_GetTime) for the `GetTime()` function.

I honestly can say I never expected it to return the time since your computer booted up. Haha

I'll let you know when I've pushed out a fix. 
Thanks for your assistance in troubleshooting this issue!

**Comment by cecilia-sanare** [comment]
Hey @fleetcommand this issue should now be resolved in [1.9.13](https://www.curseforge.com/wow/addons/butter-quest-tracker/files/2820152)!

Let me know if you run into any other issues!

**Comment by fleetcommand** [comment]
Thank you very much! In this case the zone division was just a strange coincidence it seems :D After update, the order seems to be fine, thanks! :)
