### ISSUE TITLE
"attempt to index global 'QuestieDB' (a nil value)"

### ISSUE THREAD

**Issue by Mizzajl** [butter-cookie-kitkat/ButterQuestTracker#81]
## Bug description

Trying to track quests by proximity, getting error:

> Date: 2019-11-18 13:18:02
> ID: 1
> Error occured in: Global
> Count: 1
> Message: ...tterQuestTracker\LibQuestHelpers\LibQuestHelpers.lua line 212:
>    attempt to index global 'QuestieDB' (a nil value)
> Debug:
>    (tail call): ?
>    (tail call): ?
>    ...tterQuestTracker\LibQuestHelpers\LibQuestHelpers.lua:212: GetDistanceToClosestObjective()
>    ...ace\AddOns\ButterQuestTracker\ButterQuestTracker.lua:220:
>       ...ace\AddOns\ButterQuestTracker\ButterQuestTracker.lua:204
>    (tail call): ?
>    [C]: sort()
>    ...ace\AddOns\ButterQuestTracker\ButterQuestTracker.lua:493: Sort()
>    ...ace\AddOns\ButterQuestTracker\ButterQuestTracker.lua:786: RefreshView()
>    ...ace\AddOns\ButterQuestTracker\ButterQuestTracker.lua:137: ?()
>    ...dler-1.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:119:
>       ...dler-1.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:119
>    [C]: ?
>    ...dler-1.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:29:
>       ...dler-1.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:25
>    ...dler-1.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: Fire()
>    ...ccountant_Classic\Libs\AceEvent-3.0\AceEvent-3.0.lua:120:
>       ...ccountant_Classic\Libs\AceEvent-3.0\AceEvent-3.0.lua:119
> Locals:
> None
> 

**Butter Quest Tracker Version:** 

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AccountantClassic, vv2.11.08.11302
  AdvancedInterfaceOptions, v1.3.3
  alaTalentEmu, v113r.191106
  ArkInventory, v30903
  ArkInventoryRules, v20000
  ArkInventoryRulesExample, v20000
  ArkInventorySearch, v20000
  Atlas, vv1.45.01.11302
  AtlasClassicWoW, vv1.45.00.11302.05
  AtlasLootClassic, vv1.3.4
  AtlasLootClassicData, vv1.3.4
  AtlasLootClassicDungeonsAndRaids, vv1.3.4
  AtlasLootClassicMaps, vv1.0.0
  AtlasQuest, v4.11.57
  ATTClassic, v0.1.2
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  aucadvancedsearcherpawn, v1.6.1-classic
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucScanData, v8.2.6365 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  auxaddon, v0.8.4
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  BiSTracker, v1.4 
  BootyBayGazette, v6.0.20191118
  BrokerAnything, vv1.6-classic
  ButterQuestTracker, v1.9.15
  CallbackHandler10, v
  ClassicAuraDurations, v
  ClassicThreatMeter, v1.10
  ConROC, v1.13.34
  ConROCShaman, v1.13.2
  DBMCore, v1.13.18
  DBMDefaultSkin, v
  DBMSoundEventsPack, v1.6.3
  DBMStatusBarTimers, v
  Decursive, v2.7.6.5
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  Dominos, v8.2.30
  DominosCast, v
  DominosEncounter, v
  DominosProgress, v
  DominosRoll, v
  ElkBuffBars, v2.6.0-196
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  FiveSecondRule, v1.15
  Guidelime, v1.036
  GuidelimeBusteas160leveling, v1.8.0-Release
  GuidelimeDungeonQuests, v0.14.2
  GuideLimeTUGs5man, v1.0
  GuildHelperClassic, v0.2.3
  HealBot, v1.13.2.10
  HealBotTips, v1.13.2.10
  HideRaidManager, v1.0.1
  idTip, v8.2.1
  Informant, v8.2.6374 (SwimmingSeadragon)
  ItemRack, v
  LeatrixMaps, v1.13.36
  LeatrixPlus, v1.13.37
  LibStub, v
  MobInfo2Classic, v11302.04
  OmniCC, v8.2.5
  Pawn, v2.3.11
  Quartz, v3.5-classic-5
  QuestFrameFixer, v1.1.1
  QuestIconDesaturation, v3.1
  Questie, v5.2.1
  RecipeRadarClassic, v1.0.0.23
  Regen, v0.1.4
  SilverDragon, vv11302.0
  SilverDragonClassic, vv11302.0
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Spy, v1.0.14
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TellMeWhen, v8.7.3
  TidyPlatesThreatPlates, v1.2.6
  TitanAttributesMulti, v1.1
  TitanClassic, v1.1.3.11302
  TitanClassicItemDed, v1.0.0.3
  TitanClassicLocation, v1.1.3.11302
  TitanClassicLootType, v1.1.3.11302
  TitanClassicMail, v1.0.0.1
  TitanClassicPerformance, v1.1.3.11302
  TitanClassicReagentTracker, v1.13.2 (1.0.6)
  TitanClassicRecZone, v1.0.0.5
  TitanClassicRepair, v1.1.3.11302
  TitanClassicRestPlus, v1.0.0.1
  TomTom, vv11302-1.0.8
  TotemTimers, v1.06
  TradeSkillMaster, vv4.8.20
  WeakAuras, v2.15.5
  WeaponSwingTimer, v4.1.0
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=bbc)

**Comment by cecilia-sanare** [comment]
Hey @Mizzajl this should now be resolved in [1.9.16](https://www.curseforge.com/wow/addons/butter-quest-tracker/files/2829168).

Let me know if you run into any other issues!
