### ISSUE TITLE
Support for ElvUI?

### ISSUE THREAD

**Issue by Gogo1951** [butter-cookie-kitkat/ButterQuestTracker#92]
## Question

Hey guys, I think this addon is spot on what I'm looking for... but it's doubling up on top of my ElvUI quest objective tracker. Latest versions of both.

I saw some comments in other issues, and it seems you do have support for ElvUI... any ideas what I may have done to jack this up so much? I've done some layout modifications to ElvUI, but just like moving unit frames around, and I use a different bag tracker so I turned bags off. That sort of thing. No code changes.

![WoWScrnShot_120119_212136](https://user-images.githubusercontent.com/55365231/69928270-c283ac00-1480-11ea-9627-35287c11585d.jpg)

**Comment by Gogo1951** [comment]
It does sort of fix itself after a few seconds.

## Fixed

![WoWScrnShot_120119_220808](https://user-images.githubusercontent.com/55365231/69930082-345ef400-1487-11ea-8790-33d58d5df9b3.jpg)

## Change Zones and Broken Again

![WoWScrnShot_120119_220817](https://user-images.githubusercontent.com/55365231/69930086-37f27b00-1487-11ea-87c9-20ea8a81f500.jpg)

**Comment by cecilia-sanare** [comment]
Hey @Gogo1951!

Thanks for taking the time to submit an issue!

Do you happen to have Questie installed?
If so can you verify that isn't Questie's Tracker by ensuring that it's disabled?
